"use client"

import { useState } from "react"
import Link from "next/link"
import { useParams, useRouter } from "next/navigation"
import { Archive, ArrowLeft, Building2, CalendarDays, Camera, CheckCircle2, Clock3, ExternalLink, MapPin, MessageSquareMore, Package, PackageCheck, RotateCcw, Send, ShoppingCart, Upload, User, XCircle } from "lucide-react"
import { useApp } from "@/lib/store"
import type { Comment, SupplyStatus } from "@/lib/types"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { SupplyApprovalBadge, SupplyPriorityBadge, SupplyStatusBadge } from "@/components/supply-badges"

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" })
const steps: Array<{ label: string; status: SupplyStatus }> = [
  { label: "Submitted", status: "Submitted" }, { label: "Ready to Order", status: "Ready to Order" },
  { label: "Ordered", status: "Ordered" }, { label: "Received", status: "Received" },
]

function Meta({ icon: Icon, label, children }: { icon: React.ElementType; label: string; children: React.ReactNode }) {
  return <div className="min-w-0"><dt className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground"><Icon className="h-3 w-3" />{label}</dt><dd className="mt-1 text-sm font-medium text-foreground">{children}</dd></div>
}

export default function SupplyRequestDetailPage() {
  const { id } = useParams<{ id: string }>()
  const router = useRouter()
  const { role, currentUser, supplyRequests, locations, comments, activity, addComment, updateSupplyRequest, archiveSupplyRequest, restoreSupplyRequest, addSupplyPhoto, showToast } = useApp()
  const [commentText, setCommentText] = useState("")
  const request = supplyRequests.find((item) => item.id === id)

  if (!request) return <div className="rounded-xl border border-dashed border-border bg-card p-10 text-center"><Package className="mx-auto h-8 w-8 text-muted-foreground" /><h1 className="mt-3 font-semibold">Supply request not found</h1><p className="mt-1 text-sm text-muted-foreground">It may be outside your assigned location.</p><Button render={<Link href="/supply-requests" />} nativeButton={false} variant="outline" className="mt-4">Back to Supply Requests</Button></div>

  const location = locations.find((item) => item.id === request.locationId)
  const requestComments = comments.filter((comment) => comment.recordId === id).sort((a, b) => a.timestamp.localeCompare(b.timestamp))
  const requestActivity = activity.filter((event) => event.recordId === id).sort((a, b) => b.timestamp.localeCompare(a.timestamp))
  const progressIndex = request.approvalStatus === "Awaiting Approval" || request.approvalStatus === "Declined" ? 0 : Math.max(0, steps.findIndex((step) => step.status === request.fulfillmentStatus))
  const stopped = request.approvalStatus === "Declined" || request.fulfillmentStatus === "Cancelled"
  const canEdit = !request.archived && (role === "owner" || (["Submitted", "Ready to Order"].includes(request.fulfillmentStatus) && request.approvalStatus !== "Approved"))

  const changeStatus = (status: SupplyStatus) => updateSupplyRequest(id, {
    fulfillmentStatus: status,
    orderedAt: status === "Ordered" ? new Date().toISOString() : request.orderedAt,
    receivedAt: status === "Received" ? new Date().toISOString() : request.receivedAt,
  }, status === "Ordered" ? "Item ordered." : status === "Received" ? "Item received." : status === "Cancelled" ? "Supply request cancelled." : "Request marked Ready to Order.")

  const submitComment = () => {
    if (!commentText.trim()) return
    const comment: Comment = { id: `scmt_${Date.now()}`, recordId: id, user: currentUser.name, userId: currentUser.id, role: currentUser.role, text: commentText.trim(), timestamp: new Date().toISOString(), isUnread: false }
    addComment(comment); setCommentText("")
  }

  return <div className="mx-auto max-w-6xl space-y-5">
    <Link href="/supply-requests" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Back to Supply Requests</Link>
    <section className="overflow-hidden rounded-xl border border-border bg-card shadow-sm">
      <div className="border-b border-border p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><span className="text-xs font-semibold uppercase tracking-wide text-teal-700">Supply request</span><h1 className="mt-2 text-xl font-semibold leading-tight sm:text-2xl">{request.itemName}</h1><p className="mt-2 text-sm text-muted-foreground">Request {request.id} · Last updated {new Date(request.lastUpdated).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</p></div><div className="flex flex-wrap gap-2"><SupplyPriorityBadge priority={request.priority} /><SupplyApprovalBadge status={request.approvalStatus} /><SupplyStatusBadge status={request.fulfillmentStatus} /></div></div></div>
      <div className="bg-muted/15 px-4 py-4 sm:px-6"><div className="mb-4 flex items-center justify-between gap-2"><p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">Supply fulfillment</p>{request.approvalStatus === "Awaiting Approval" && <SupplyApprovalBadge status="Awaiting Approval" />}</div><ol className="grid grid-cols-4" aria-label={`Supply progress: ${request.fulfillmentStatus}`}>{steps.map((step, index) => { const completed = index < progressIndex; const current = index === progressIndex; const finished = request.fulfillmentStatus === "Received" && index === 3; return <li key={step.label} className="relative flex min-w-0 flex-col items-center text-center" aria-current={current ? "step" : undefined}>{index < 3 && <span className={cn("absolute left-[calc(50%+0.875rem)] top-[13px] h-0.5 w-[calc(100%-1.75rem)]", index < progressIndex && !stopped ? "bg-emerald-500" : "bg-slate-200")} />}<span className={cn("relative z-10 flex h-7 w-7 items-center justify-center rounded-full border text-[11px] font-semibold transition-colors", completed && !stopped && "border-emerald-600 bg-emerald-600 text-white", current && !stopped && !finished && "border-blue-600 bg-blue-600 text-white ring-4 ring-blue-100", (finished || completed) && !stopped && "border-emerald-600 bg-emerald-600 text-white", stopped && current && "border-rose-300 bg-rose-50 text-rose-700 ring-4 ring-rose-100", !completed && !current && "border-slate-200 bg-card text-slate-400")}>{completed || finished ? <CheckCircle2 className="h-4 w-4" /> : index + 1}</span><span className={cn("mt-2 max-w-24 text-[10px] font-medium leading-tight sm:text-xs", current ? "text-foreground" : "text-muted-foreground")}>{step.label}</span></li> })}</ol></div>
    </section>

    <div className="grid gap-5 lg:grid-cols-3"><div className="contents lg:col-span-2 lg:block lg:space-y-5">
      <section className="rounded-xl border border-border bg-card p-5 shadow-sm"><h2 className="text-sm font-semibold">Request details</h2><dl className="mt-4 grid grid-cols-2 gap-x-5 gap-y-5 sm:grid-cols-3"><Meta icon={MapPin} label="Location">{location?.name ?? "—"}</Meta><Meta icon={Building2} label="Classroom / Area">{request.area ?? "Not specified"}</Meta><Meta icon={Package} label="Category">{request.category}</Meta><Meta icon={User} label="Requested by">{request.requestedBy}</Meta><Meta icon={CalendarDays} label="Requested">{new Date(request.requestedAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</Meta><Meta icon={Clock3} label="Needed by">{request.neededBy ? new Date(`${request.neededBy}T12:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) : "Not specified"}</Meta></dl><div className="mt-5 rounded-lg bg-muted/40 p-4"><p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">Description / Reason</p><p className="mt-1.5 text-sm leading-relaxed">{request.description}</p></div>{request.approvalNote && <div className="mt-3 rounded-lg border border-amber-200 bg-amber-50/55 p-3"><p className="text-xs font-semibold text-amber-800">Approval note</p><p className="mt-1 text-sm">{request.approvalNote}</p></div>}</section>
      <section className="rounded-xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Request photo</h2><p className="mt-0.5 text-xs text-muted-foreground">Prototype attachments preserve filenames and history.</p></div><span className="rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground">{request.photos.length}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{request.photos.map((photo) => <button type="button" key={`${photo.name}-${photo.uploadedAt}`} onClick={() => showToast(`Attachment ready: ${photo.name}`)} className="flex items-center gap-2 rounded-lg border border-border p-3 text-left text-xs hover:bg-muted/40"><Camera className="h-4 w-4 text-muted-foreground" /><span className="truncate">{photo.name}</span></button>)}{request.photos.length === 0 && <p className="text-sm text-muted-foreground">No photo attached.</p>}</div>{canEdit && <label className="mt-3 flex cursor-pointer items-center justify-center gap-1.5 rounded-md border border-dashed border-border px-3 py-2 text-xs font-medium text-primary hover:bg-primary/5"><Upload className="h-3.5 w-3.5" />Attach photo<input type="file" className="sr-only" accept="image/*" onChange={(e) => { const file = e.target.files?.[0]; if (file) addSupplyPhoto(id, file.name); e.target.value = "" }} /></label>}</section>
      <section className="rounded-xl border border-border bg-card p-5 shadow-sm"><h2 className="text-sm font-semibold">Comments and notes <span className="font-normal text-muted-foreground">({requestComments.length})</span></h2><div className="mt-4 space-y-4">{requestComments.map((comment) => <div key={comment.id} className="flex gap-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-teal-100 text-xs font-semibold text-teal-700">{comment.user.split(" ").map((part) => part[0]).join("")}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline gap-2"><span className="text-sm font-medium">{comment.user}</span><span className="text-[10px] capitalize text-muted-foreground">{comment.role.replace("_", " ")}</span><span className="ml-auto text-[10px] text-muted-foreground">{new Date(comment.timestamp).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</span></div><p className="mt-1 rounded-lg bg-muted/40 px-3.5 py-3 text-sm">{comment.text}</p></div></div>)}{requestComments.length === 0 && <p className="text-sm text-muted-foreground">No comments yet.</p>}</div>{!request.archived && <div className="mt-4 flex gap-3"><Textarea rows={3} value={commentText} onChange={(e) => setCommentText(e.target.value)} placeholder="Add a note or answer an approval question…" /><Button size="sm" className="self-end gap-1.5" onClick={submitComment} disabled={!commentText.trim()}><Send className="h-3.5 w-3.5" />Add</Button></div>}</section>
    </div><aside className="contents lg:block lg:space-y-5">
      {role === "owner" && !request.archived && <section className="rounded-xl border border-border bg-card p-5 shadow-sm"><h2 className="text-sm font-semibold">Owner approval</h2><p className="mt-1 text-xs text-muted-foreground">Approval remains separate from ordering progress.</p><div className="mt-3 space-y-2"><Button className="w-full justify-start gap-2 bg-emerald-600 hover:bg-emerald-600/90" size="sm" onClick={() => updateSupplyRequest(id, { approvalStatus: "Approved", fulfillmentStatus: request.fulfillmentStatus === "Submitted" ? "Ready to Order" : request.fulfillmentStatus, needsMoreInfo: false, approvalNote: "Approved by Owner." }, "Owner approved the supply request.")} disabled={request.approvalStatus === "Approved"}><CheckCircle2 className="h-4 w-4" />Approve</Button><Button variant="outline" className="w-full justify-start gap-2 text-amber-700" size="sm" onClick={() => updateSupplyRequest(id, { needsMoreInfo: true, approvalNote: "Owner requested more information before approval." }, "More information requested.")}><MessageSquareMore className="h-4 w-4" />Request more information</Button><Button variant="outline" className="w-full justify-start gap-2 text-rose-700" size="sm" onClick={() => updateSupplyRequest(id, { approvalStatus: "Declined", approvalNote: "Declined by Owner." }, "Owner declined the supply request.")} disabled={request.approvalStatus === "Declined"}><XCircle className="h-4 w-4" />Decline</Button></div></section>}
      <section className="rounded-xl border border-border bg-card p-5 shadow-sm"><h2 className="text-sm font-semibold">Fulfillment</h2><div className="mt-3 grid gap-2"><Button variant="outline" size="sm" className="justify-start gap-2" onClick={() => changeStatus("Ready to Order")} disabled={!canEdit || request.approvalStatus === "Awaiting Approval" || request.fulfillmentStatus === "Ready to Order"}><CheckCircle2 className="h-4 w-4 text-blue-600" />Ready to Order</Button>{role === "owner" && <Button variant="outline" size="sm" className="justify-start gap-2" onClick={() => changeStatus("Ordered")} disabled={request.approvalStatus === "Awaiting Approval" || request.fulfillmentStatus === "Ordered"}><ShoppingCart className="h-4 w-4 text-indigo-600" />Mark Ordered</Button>}<Button variant="outline" size="sm" className="justify-start gap-2" onClick={() => changeStatus("Received")} disabled={request.fulfillmentStatus !== "Ordered"}><PackageCheck className="h-4 w-4 text-emerald-600" />Mark Received</Button>{role === "owner" && <Button variant="ghost" size="sm" className="justify-start gap-2 text-rose-700" onClick={() => changeStatus("Cancelled")} disabled={request.fulfillmentStatus === "Cancelled"}><XCircle className="h-4 w-4" />Cancel</Button>}</div></section>
      <section className="rounded-xl border border-border bg-card p-5 shadow-sm"><h2 className="text-sm font-semibold">Quantity and cost</h2><dl className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-lg bg-muted/40 p-3"><dt className="text-[10px] font-semibold uppercase text-muted-foreground">Quantity</dt><dd className="mt-1 text-sm font-semibold">{request.quantity} {request.quantityUnit ?? ""}</dd></div><div className="rounded-lg bg-muted/40 p-3"><dt className="text-[10px] font-semibold uppercase text-muted-foreground">Unit cost</dt><dd className="mt-1 text-sm font-semibold tabular-nums">{request.unitCost != null ? money.format(request.unitCost) : "—"}</dd></div><div className="col-span-2 rounded-lg border border-teal-200 bg-teal-50/50 p-3"><dt className="text-[10px] font-semibold uppercase text-teal-700">Estimated total</dt><dd className="mt-1 text-xl font-bold tabular-nums">{money.format(request.estimatedTotal)}</dd></div></dl><div className="mt-4 space-y-3 border-t border-border pt-4"><div><p className="text-[10px] font-semibold uppercase text-muted-foreground">Vendor / Store</p><p className="mt-1 text-sm">{request.vendor ?? "Not specified"}</p></div>{request.productLink && <a href={request.productLink} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline">View product link <ExternalLink className="h-3 w-3" /></a>}</div></section>
      <section className="rounded-xl border border-border bg-card p-5 shadow-sm"><h2 className="text-sm font-semibold">Activity history</h2><div className="mt-4 space-y-4">{requestActivity.map((event, index) => <div key={event.id} className="relative flex gap-3">{index < requestActivity.length - 1 && <span className="absolute left-3.5 top-7 h-full w-px bg-border" />}<span className="z-10 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-border bg-card"><Clock3 className="h-3 w-3 text-muted-foreground" /></span><div className="pb-1"><p className="text-xs font-medium leading-snug">{event.detail}</p><p className="mt-1 text-[10px] text-muted-foreground">{event.user} · {new Date(event.timestamp).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</p></div></div>)}</div></section>
      {role === "owner" && <section className="rounded-xl border border-border bg-card p-4 shadow-sm">{request.archived ? <Button variant="outline" className="w-full justify-start gap-2" onClick={() => restoreSupplyRequest(id)}><RotateCcw className="h-4 w-4" />Restore request</Button> : <Button variant="outline" className="w-full justify-start gap-2 text-muted-foreground" onClick={() => { archiveSupplyRequest(id); router.push("/archived") }}><Archive className="h-4 w-4" />Archive request</Button>}<p className="mt-2 text-[11px] text-muted-foreground">No permanent delete. Full history remains intact.</p></section>}
    </aside></div>
  </div>
}
