import type {
  Location,
  ComplianceRecord,
  ActivityEvent,
  Comment,
  Notification,
  User,
  ClassroomAgeGroup,
  ComplianceCategory,
  MaintenanceRequestDraft,
  OperationsRecordType,
} from "./types"

export const COMPLIANCE_CATEGORIES: ComplianceCategory[] = [
  "Licensing",
  "Health & Safety Drills",
  "Child Files",
  "Staff Files",
  "Classroom Observations",
  "CCIR / Critical Incidents",
  "Parent Complaints",
  "Staff Complaints",
]

export const OPERATIONS_RECORD_TYPES: OperationsRecordType[] = [
  "Opening Checklist",
  "Closing Checklist",
  "Playground Checklist",
  "Other Operations Record",
]

export const CLASSROOM_AGE_GROUPS: ClassroomAgeGroup[] = [
  "Infant",
  "Toddler",
  "Twaddler",
  "Prepper",
  "Preschool",
]

export const USERS: User[] = [
  { id: "u1", name: "Sandra Mitchell", role: "owner", initials: "SM" },
  { id: "u2", name: "Rachel Torres", role: "director", locationId: "loc1", initials: "RT" },
  { id: "u3", name: "James Okafor", role: "director", locationId: "loc2", initials: "JO" },
  { id: "u4", name: "Priya Nair", role: "director", locationId: "loc3", initials: "PN" },
  { id: "u5", name: "Morgan Ellis", role: "assistant_director", locationId: "loc2", initials: "ME" },
]

export const LOCATIONS: Location[] = [
  {
    id: "loc1",
    name: "Lake Mary Learning Center",
    director: "Rachel Torres",
    directorId: "u2",
    address: "1420 Crystal Lake Rd, Lake Mary, FL 32746",
    phone: "(407) 555-0182",
    capacity: 72,
  },
  {
    id: "loc2",
    name: "Winter Park Learning Center",
    director: "James Okafor",
    directorId: "u3",
    address: "310 Fairbanks Ave, Winter Park, FL 32789",
    phone: "(407) 555-0241",
    capacity: 88,
  },
  {
    id: "loc3",
    name: "Sanford Learning Center",
    director: "Priya Nair",
    directorId: "u4",
    address: "2850 Orlando Dr, Sanford, FL 32773",
    phone: "(407) 555-0317",
    capacity: 64,
  },
]

export const RECORDS: ComplianceRecord[] = [
  {
    id: "rec16",
    title: "Opening Checklist — August 2025",
    locationId: "loc1",
    category: "Operations",
    workspace: "operations",
    recordType: "Opening Checklist",
    status: "New",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-08-08",
    lastUpdated: "2025-08-08",
    description: "Recurring opening checklist covering facility walk-through, classroom readiness, playground inspection, and required opening documentation.",
    fileNames: ["Opening_Checklist_August_2025.pdf"],
    tags: ["opening checklist", "monthly", "operations"],
  },
  {
    id: "rec17",
    title: "Closing Checklist — August 2025",
    locationId: "loc2",
    category: "Operations",
    workspace: "operations",
    recordType: "Closing Checklist",
    status: "Reviewed",
    uploadedBy: "Morgan Ellis",
    uploadedById: "u5",
    uploadDate: "2025-08-08",
    lastUpdated: "2025-08-08",
    description: "End-of-day operational checklist covering classroom closeout, alarm procedures, medication storage, and final facility walk-through.",
    fileNames: ["Closing_Checklist_August_2025.pdf"],
    tags: ["closing checklist", "monthly", "operations"],
  },
  {
    id: "rec18",
    title: "Playground Checklist — August 2025",
    locationId: "loc3",
    category: "Operations",
    workspace: "operations",
    recordType: "Playground Checklist",
    classroomAgeGroup: "Preschool",
    area: "North Playground",
    status: "Needs Attention",
    uploadedBy: "Priya Nair",
    uploadedById: "u4",
    uploadDate: "2025-08-07",
    lastUpdated: "2025-08-08",
    description: "Monthly playground readiness checklist. Follow-up requested for the north gate latch before the next outdoor period.",
    fileNames: ["Playground_Checklist_August_2025.pdf", "North_Gate_Latch.jpg"],
    tags: ["playground", "monthly", "operations"],
  },
  {
    id: "rec19",
    title: "Operations — Kitchen Inventory Review",
    locationId: "loc1",
    category: "Operations",
    workspace: "operations",
    recordType: "Other Operations Record",
    area: "Kitchen",
    status: "Archived",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-07-18",
    lastUpdated: "2025-08-01",
    description: "One-time operational review of kitchen inventory labeling, storage rotation, and receiving documentation.",
    fileNames: ["Kitchen_Inventory_Review.pdf"],
    tags: ["kitchen", "inventory", "operations"],
  },
  {
    id: "rec15",
    title: "Infant Classroom Observation — August",
    locationId: "loc1",
    category: "Classroom Observations",
    classroomAgeGroup: "Infant",
    observationMonth: "2025-08",
    status: "Reviewed",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-08-06",
    lastUpdated: "2025-08-07",
    description: "Monthly classroom observation focused on arrival routines, safe sleep documentation, and responsive caregiving. Notes reviewed with the lead teacher.",
    fileNames: ["Infant_Observation_August_2025.pdf", "Infant_Room_August.jpg"],
    tags: ["monthly observation", "infant", "August"],
  },
  {
    id: "rec14",
    title: "Toddler Classroom Observation — August",
    locationId: "loc2",
    category: "Classroom Observations",
    classroomAgeGroup: "Toddler",
    observationMonth: "2025-08",
    status: "Needs Attention",
    uploadedBy: "Morgan Ellis",
    uploadedById: "u5",
    uploadDate: "2025-08-05",
    lastUpdated: "2025-08-06",
    description: "Monthly observation of transitions, supervision, and learning-center setup. Follow-up requested for transition coverage notes.",
    fileNames: ["Toddler_Observation_August_2025.pdf"],
    tags: ["monthly observation", "toddler", "follow-up"],
  },
  {
    id: "rec13",
    title: "Preschool Classroom Observation — August",
    locationId: "loc3",
    category: "Classroom Observations",
    classroomAgeGroup: "Preschool",
    observationMonth: "2025-08",
    status: "New",
    uploadedBy: "Priya Nair",
    uploadedById: "u4",
    uploadDate: "2025-08-05",
    lastUpdated: "2025-08-05",
    description: "Monthly observation covering classroom organization, active supervision, and lesson-plan alignment.",
    fileNames: ["Preschool_Observation_August_2025.pdf", "Preschool_Centers_August.jpg"],
    tags: ["monthly observation", "preschool", "August"],
  },
  {
    id: "rec1",
    title: "Annual DCF Licensing Renewal – 2025",
    locationId: "loc1",
    category: "Licensing",
    status: "Needs Attention",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-07-28",
    lastUpdated: "2025-07-30",
    description:
      "Annual license renewal application submitted to DCF. Awaiting signed director attestation page before final submission.",
    fileNames: ["DCF_License_Renewal_2025_Draft.pdf"],
    tags: ["DCF", "annual", "renewal"],
    relatedRef: "Staff: Rachel Torres",
  },
  {
    id: "rec2",
    title: "Fire Drill – July 2025",
    locationId: "loc1",
    category: "Health & Safety Drills",
    status: "New",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-07-22",
    lastUpdated: "2025-07-22",
    description:
      "Monthly fire drill conducted at 10:15 AM. All 68 children and 9 staff evacuated within 2 minutes 38 seconds. No issues noted.",
    fileNames: ["Fire_Drill_July2025_LM.pdf", "Fire_Drill_July2025_photo.jpg"],
    tags: ["fire drill", "monthly", "evacuation"],
  },
  {
    id: "rec3",
    title: "Child Enrollment File – Aiden Clark",
    locationId: "loc1",
    category: "Child Files",
    status: "Reviewed",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-07-10",
    lastUpdated: "2025-07-15",
    description:
      "Complete enrollment packet for Aiden Clark (DOB 03/14/2021). Includes immunization records, emergency contacts, and signed parent handbook acknowledgment.",
    fileNames: ["Clark_Aiden_Enrollment_2025.pdf"],
    tags: ["enrollment", "new child"],
    relatedRef: "Child: Aiden Clark",
  },
  {
    id: "rec4",
    title: "Staff Background Check – Maria Gonzalez",
    locationId: "loc2",
    category: "Staff Files",
    status: "Reviewed",
    uploadedBy: "James Okafor",
    uploadedById: "u3",
    uploadDate: "2025-07-05",
    lastUpdated: "2025-07-08",
    description:
      "Level 2 background screening results for Maria Gonzalez. Clear results received. File updated in DCF portal.",
    fileNames: ["Gonzalez_Maria_L2_Clearance.pdf"],
    tags: ["background check", "Level 2", "new hire"],
    relatedRef: "Staff: Maria Gonzalez",
  },
  {
    id: "rec5",
    title: "Parent Complaint – Incident Report #2025-019",
    locationId: "loc2",
    category: "Parent Complaints",
    status: "Needs Attention",
    uploadedBy: "James Okafor",
    uploadedById: "u3",
    uploadDate: "2025-07-25",
    lastUpdated: "2025-07-27",
    description:
      "Parent complaint received regarding playground supervision on 7/24. Full written statement and director response attached. Follow-up meeting scheduled.",
    fileNames: ["ParentComplaint_2025-019.pdf", "DirectorResponse_2025-019.pdf"],
    tags: ["complaint", "playground", "supervision"],
  },
  {
    id: "rec6",
    title: "CCIR – Allergic Reaction Incident",
    locationId: "loc3",
    category: "CCIR / Critical Incidents",
    status: "Needs Attention",
    uploadedBy: "Priya Nair",
    uploadedById: "u4",
    uploadDate: "2025-07-29",
    lastUpdated: "2025-07-29",
    description:
      "Child experienced mild allergic reaction during snack time. Epi-pen administered by nurse. Parent notified. DCF reportable incident form submitted within 1-hour window.",
    fileNames: ["CCIR_AllergyIncident_072925.pdf", "EpipenAdmin_Log.pdf"],
    tags: ["CCIR", "medical", "reportable", "urgent"],
  },
  {
    id: "rec7",
    title: "Lockdown Drill – June 2025",
    locationId: "loc2",
    category: "Health & Safety Drills",
    status: "Reviewed",
    uploadedBy: "James Okafor",
    uploadedById: "u3",
    uploadDate: "2025-06-18",
    lastUpdated: "2025-06-20",
    description:
      "Quarterly lockdown drill completed in coordination with Seminole County Sheriff. All rooms secured within 90 seconds.",
    fileNames: ["Lockdown_Drill_June2025_WP.pdf"],
    tags: ["lockdown", "quarterly", "security"],
  },
  {
    id: "rec8",
    title: "State Licensing Inspection – 2025",
    locationId: "loc3",
    category: "Licensing",
    status: "New",
    uploadedBy: "Priya Nair",
    uploadedById: "u4",
    uploadDate: "2025-07-31",
    lastUpdated: "2025-07-31",
    description:
      "Unannounced state licensing inspection completed on 7/31. Inspector: Jennifer Walsh. No citations issued. Inspection report attached.",
    fileNames: ["StateInspection_2025_Sanford.pdf"],
    tags: ["inspection", "state", "DCF"],
  },
  {
    id: "rec9",
    title: "Staff Complaint – Workplace Conduct",
    locationId: "loc1",
    category: "Staff Complaints",
    status: "New",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-08-01",
    lastUpdated: "2025-08-01",
    description:
      "Written complaint filed by classroom aide regarding conduct of lead teacher. HR investigation initiated. All parties notified.",
    fileNames: ["StaffComplaint_HR_080125.pdf"],
    tags: ["HR", "conduct", "investigation"],
  },
  {
    id: "rec10",
    title: "Child Enrollment File – Sofia Rivera",
    locationId: "loc3",
    category: "Child Files",
    status: "New",
    uploadedBy: "Priya Nair",
    uploadedById: "u4",
    uploadDate: "2025-08-04",
    lastUpdated: "2025-08-04",
    description:
      "New enrollment packet for Sofia Rivera (DOB 11/02/2020). Immunization records pending. Enrollment contingent on receipt within 30 days.",
    fileNames: ["Rivera_Sofia_Enrollment_2025.pdf"],
    tags: ["enrollment", "pending immunization"],
    relatedRef: "Child: Sofia Rivera",
  },
  {
    id: "rec11",
    title: "CPR / First Aid Certification – Staff Renewal",
    locationId: "loc2",
    category: "Staff Files",
    status: "Reviewed",
    uploadedBy: "James Okafor",
    uploadedById: "u3",
    uploadDate: "2025-06-30",
    lastUpdated: "2025-07-02",
    description:
      "Renewed CPR and First Aid certifications for 6 staff members. Certificates valid through June 2027. All records updated in staff files.",
    fileNames: ["CPR_Certifications_June2025_WP.pdf"],
    tags: ["CPR", "certification", "renewal"],
  },
  {
    id: "rec12",
    title: "Tornado Drill – May 2025",
    locationId: "loc1",
    category: "Health & Safety Drills",
    status: "Archived",
    uploadedBy: "Rachel Torres",
    uploadedById: "u2",
    uploadDate: "2025-05-14",
    lastUpdated: "2025-06-01",
    description:
      "Annual tornado drill completed. All children moved to interior hallways within 85 seconds. Archived after review cycle.",
    fileNames: ["Tornado_Drill_May2025_LM.pdf"],
    tags: ["tornado", "annual", "weather"],
  },
]

export const FUTURE_MAINTENANCE_INSIGHT: MaintenanceRequestDraft = {
  id: "maint-concept-1",
  locationId: "loc2",
  classroomAgeGroup: "Toddler",
  area: "Toddler restroom",
  category: "Plumbing",
  asset: "North toilet",
  vendor: "Sunstate Facility Services",
  estimatedCost: 740,
  invoiceFileNames: ["invoice-1048.pdf", "invoice-1116.pdf", "invoice-1192.pdf"],
  repeatIssueKey: "loc2-toddler-north-toilet",
}

export const ACTIVITY: ActivityEvent[] = [
  {
    id: "act19",
    recordId: "rec19",
    type: "archived",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-08-01T15:05:00",
    detail: "Kitchen inventory review archived after the operational follow-up was completed.",
  },
  {
    id: "act18",
    recordId: "rec18",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-08-08T09:20:00",
    detail: "Playground checklist marked Needs Attention.",
  },
  {
    id: "act17",
    recordId: "rec17",
    type: "created",
    user: "Morgan Ellis",
    userId: "u5",
    role: "assistant_director",
    timestamp: "2025-08-08T17:40:00",
    detail: "Closing checklist uploaded for August.",
  },
  {
    id: "act16",
    recordId: "rec16",
    type: "created",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    timestamp: "2025-08-08T08:10:00",
    detail: "Opening checklist uploaded for August.",
  },
  {
    id: "act15",
    recordId: "rec15",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-08-07T14:10:00",
    detail: "Infant classroom observation marked Reviewed.",
  },
  {
    id: "act14",
    recordId: "rec14",
    type: "comment_added",
    user: "Morgan Ellis",
    userId: "u5",
    role: "assistant_director",
    timestamp: "2025-08-06T11:30:00",
    detail: "Follow-up note added to the Toddler classroom observation.",
  },
  {
    id: "act13",
    recordId: "rec13",
    type: "created",
    user: "Priya Nair",
    userId: "u4",
    role: "director",
    timestamp: "2025-08-05T16:20:00",
    detail: "Preschool monthly classroom observation uploaded.",
  },
  {
    id: "act1",
    recordId: "rec1",
    type: "created",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    timestamp: "2025-07-28T09:14:00",
    detail: "Record created and document uploaded.",
  },
  {
    id: "act2",
    recordId: "rec1",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-07-30T14:22:00",
    detail: "Status changed from New to Needs Attention.",
  },
  {
    id: "act3",
    recordId: "rec2",
    type: "created",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    timestamp: "2025-07-22T11:05:00",
    detail: "Record created. Drill log and photo uploaded.",
  },
  {
    id: "act4",
    recordId: "rec3",
    type: "created",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    timestamp: "2025-07-10T08:30:00",
    detail: "Enrollment file created.",
  },
  {
    id: "act5",
    recordId: "rec3",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-07-15T10:11:00",
    detail: "Status changed to Reviewed.",
  },
  {
    id: "act6",
    recordId: "rec5",
    type: "created",
    user: "James Okafor",
    userId: "u3",
    role: "director",
    timestamp: "2025-07-25T15:40:00",
    detail: "Complaint report uploaded.",
  },
  {
    id: "act7",
    recordId: "rec5",
    type: "status_changed",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-07-27T09:05:00",
    detail: "Status changed to Needs Attention.",
  },
  {
    id: "act8",
    recordId: "rec6",
    type: "created",
    user: "Priya Nair",
    userId: "u4",
    role: "director",
    timestamp: "2025-07-29T13:58:00",
    detail: "CCIR record created. Two documents uploaded.",
  },
  {
    id: "act9",
    recordId: "rec8",
    type: "created",
    user: "Priya Nair",
    userId: "u4",
    role: "director",
    timestamp: "2025-07-31T16:30:00",
    detail: "Inspection report uploaded.",
  },
  {
    id: "act10",
    recordId: "rec9",
    type: "created",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    timestamp: "2025-08-01T08:45:00",
    detail: "Staff complaint record created.",
  },
  {
    id: "act11",
    recordId: "rec10",
    type: "created",
    user: "Priya Nair",
    userId: "u4",
    role: "director",
    timestamp: "2025-08-04T10:20:00",
    detail: "New enrollment file created. Immunization records pending.",
  },
  {
    id: "act12",
    recordId: "rec12",
    type: "archived",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    timestamp: "2025-06-01T11:00:00",
    detail: "Record archived after review cycle.",
  },
]

export const COMMENTS: Comment[] = [
  {
    id: "cmt1",
    recordId: "rec1",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    text: "Rachel, can you upload the signed director attestation page so we can submit the full renewal package? DCF deadline is August 15th.",
    timestamp: "2025-07-30T14:25:00",
    isUnread: false,
  },
  {
    id: "cmt2",
    recordId: "rec1",
    user: "Rachel Torres",
    userId: "u2",
    role: "director",
    text: "Understood. I have the signed page in hand — uploading the corrected version now.",
    timestamp: "2025-07-30T16:10:00",
    isUnread: true,
  },
  {
    id: "cmt3",
    recordId: "rec5",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    text: "James, please confirm the follow-up meeting date and share the parent's written response once received.",
    timestamp: "2025-07-27T09:07:00",
    isUnread: false,
  },
  {
    id: "cmt4",
    recordId: "rec5",
    user: "James Okafor",
    userId: "u3",
    role: "director",
    text: "Follow-up meeting is scheduled for August 5th at 2:00 PM. I will upload the parent's written response by end of week.",
    timestamp: "2025-07-28T08:30:00",
    isUnread: false,
  },
  {
    id: "cmt5",
    recordId: "rec6",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    text: "Priya, please verify that the DCF incident report was submitted within the 1-hour window and attach the confirmation number.",
    timestamp: "2025-07-29T16:00:00",
    isUnread: true,
  },
  {
    id: "cmt6",
    recordId: "rec9",
    user: "Sandra Mitchell",
    userId: "u1",
    role: "owner",
    text: "Rachel, keep HR in the loop. I want a status update by Friday.",
    timestamp: "2025-08-01T09:00:00",
    isUnread: true,
  },
]

export const NOTIFICATIONS: Notification[] = [
  {
    id: "notif1",
    type: "upload",
    title: "New record uploaded",
    message: "Priya Nair uploaded a Child Enrollment File at Sanford Learning Center.",
    timestamp: "2025-08-04T10:20:00",
    recordId: "rec10",
    isRead: false,
  },
  {
    id: "notif2",
    type: "upload",
    title: "New record uploaded",
    message: "Rachel Torres uploaded a Staff Complaint record at Lake Mary Learning Center.",
    timestamp: "2025-08-01T08:45:00",
    recordId: "rec9",
    isRead: false,
  },
  {
    id: "notif3",
    type: "attention",
    title: "Record needs attention",
    message: "CCIR – Allergic Reaction Incident at Sanford requires your review.",
    timestamp: "2025-07-29T13:58:00",
    recordId: "rec6",
    isRead: false,
  },
  {
    id: "notif4",
    type: "comment",
    title: "Director replied",
    message: "Rachel Torres replied to Annual DCF Licensing Renewal discussion.",
    timestamp: "2025-07-30T16:10:00",
    recordId: "rec1",
    isRead: true,
  },
  {
    id: "notif5",
    type: "upload",
    title: "Licensing inspection report uploaded",
    message: "Priya Nair uploaded the State Licensing Inspection report at Sanford.",
    timestamp: "2025-07-31T16:30:00",
    recordId: "rec8",
    isRead: true,
  },
]
